export const problems_attend = [
    "Estrés",
    "Depresión",
    "Trastornos de ansiedad",
    "Angustia",
    "Problemas de autoestima",
    "Trastornos adaptativos",
    "Trastornos del ánimo",
    "Trastornos Psicosomáticos",
    "Síndromes psicosomáticos",
    "Anhedonia",
    "Trastornos del sueño",
    "Problemas con los hijos",
    "Trastornos de la personalidad",
    "Fobias",
    "Agorafobia",
    "Fobia social",
    "Depresión post parto",
    "Crisis de pánico",
    "Estrés laboral",
    "Timidez, dificultad para hacer amigos",
    "Inseguridad y falta de confianza personal",
    "Duelo",
    "Baja tolerancia a la frustración",
    "Autoconocimiento",
    "Comunicación asertiva",
    "Inteligencia emocional",
]